{% set version = "1.1.0" %}
{% set hash_type = "sha256" %}
{% set hash_val = "16fa1b5b9e8bcb55cd291799ee80009d2d936cb94469064ebc6524569f8261c6" %}

package:
  name: pescador
  version: {{ version }}

source:
  fn: pescador-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pescador/pescador-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - joblib >=0.9
    - six
    - pyzmq
    - numpy

test:
  # Python imports
  imports:
    - pescador

about:
  home: http://github.com/pescadores/pescador
  license: ISC
  summary: 'Multiplex generators for incremental learning'
  license_family: OTHER

extra:
  recipe-maintainers:
    - bmcfee
